
title: 匠气
url: 'http://jiang7.net'
baseurl: '/' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: 姜琦
tagline: 前端开发
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: hotjp@126.com
phone: +86-18563129063
website: blog.jiang7.com #do not add http://
linkedin: hotjp
github: hotjp
twitter: '@hotjp'

#Update all the sections by editing the files inside _includes folder.
